name: Backup
on:
  push:
    branches:
      = main 
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Run preview
        uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev
          work-dir: conditional
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}