name: Dev
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./examples/conditional

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup AWS access
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::051126537531:role/pulumi-role-gh
          role-session-name: pulumidevsession
          aws-region: us-east-1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Run preview
        uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: dev
          cloud-url: s3://pulumi-backend-mk
          work-dir: ./examples/conditional
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}